### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by metegenez** [angeligareta/Datasets2Darknet#1]
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/mete/Documents/GitHub/Datasets2Darknet/src/general_parser.py", line 61, in <module>
    main()
  File "C:\Users\mete\.conda\envs\ee58j-proje\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mete\.conda\envs\ee58j-proje\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\mete\.conda\envs\ee58j-proje\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mete\.conda\envs\ee58j-proje\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:/Users/mete/Documents/GitHub/Datasets2Darknet/src/general_parser.py", line 51, in main
    DATASETS[dataset_index].read_dataset(output_train_text_path, output_test_text_path, output_train_dir_path, output_test_dir_path)
  File "C:\Users\mete\Documents\GitHub\Datasets2Darknet\src\datasets_parsers\lisatl_parser.py", line 145, in read_dataset
    write_data(output_filename, input_img, input_img_labels, train_text_file, output_train_dir_path, train_file)
  File "C:\Users\mete\Documents\GitHub\Datasets2Darknet\src\common_config.py", line 185, in write_data
    classes_counter_train[object_class] += 1
IndexError: list index out of range
```
I am getting this error on LISA traffic light dataset. object_class can be "9", however, I have 3 classes. So this causes an error.

**Comment by metegenez** [comment]
solution: change "traffic_sign_classes" variable into 
`def initialize_traffic_sign_classes():
    traffic_sign_classes.clear()
    traffic_sign_classes["0-tlred"] = ["stop", "stopLeft"]
    traffic_sign_classes["1-tlamber"] = ["warning", "warningLeft"]
    traffic_sign_classes["2-tlgreen"] = ["go", "goForward", "goLeft"]
    traffic_sign_classes[str(OTHER_CLASS) + "-" + OTHER_CLASS_NAME] = []`
